<?php

namespace Devnet\WorkflowBundle\Repository;

/**
 * GroupTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupTaskRepository extends TaskQueueRepository
{
}