<?php

namespace Devnet\WorkflowBundle\Repository;

/**
 * OfficeBudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficeBudgetRepository extends \Doctrine\ORM\EntityRepository
{
}
