<?php

namespace Devnet\WorkflowBundle\Repository;

/**
 * GroupTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class TaskQueueRepository extends \Doctrine\ORM\EntityRepository
{
    public function clearQueue($moduleId, $refId)
    {
        $qb = $this->createQueryBuilder('q');
        $qb
            ->delete()
            ->where('q.moduleId = :moduleId')
            ->andWhere('q.refId = :refId')
            ->setParameter('moduleId', $moduleId)
            ->setParameter('refId', $refId)
            ->getQuery()
            ->execute();;
    }

    public function getTaskItem($moduleId, $refId)
    {
        $qb = $this->createQueryBuilder('q');
        return $qb
            ->select('q.entity')
            ->where('q.moduleId = :moduleId')
            ->andWhere('q.refId = :refId')
            ->setParameter('moduleId', $moduleId)
            ->setParameter('refId', $refId)
            ->distinct(true)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
