<?php

namespace Devnet\WorkflowBundle\Repository;

/**
 * GroupTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTaskRepository extends TaskQueueRepository
{
    public function countUserTask($userId)
    {
        return $this->createQueryBuilder('t')
            ->select('COUNT(t) AS taskCount')
            ->where('t.user = :user')
            ->setParameter('user', $userId)
            ->getQuery()->getSingleScalarResult();
    }

    public function countUserTaskAndTime($userId)
    {
        $data = $this->createQueryBuilder('t')
            ->select('COUNT(t)')
            ->addSelect('MAX(t.date)')
            ->groupBy('t.user')
            ->where('t.user = :user')
            ->setParameter('user', $userId)
            ->getQuery()->getOneOrNullResult();

        if ($data == null) {
            return null;
        }

        return ['count' => $data[1], 'time' => new \DateTime($data[2]) ];
    }
}
