services:
#    devnet_workflow.example:
#        class: Devnet\WorkflowBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  Devnet\WorkflowBundle\Listeners\GuardListener:
      public: false
      autowire: true
      autoconfigure: true
      tags:
          - { name: kernel.event_subscriber }

  Devnet\WorkflowBundle\Listeners\WorkflowEnteredListener:
      autowire: true
      autoconfigure: true
      tags:
          - { name: kernel.event_subscriber }

  Devnet\WorkflowBundle\Listeners\SenderInfoSetter:
      arguments: ['@security.token_storage']
      tags:
          - { name: doctrine.event_subscriber }

  Devnet\WorkflowBundle\Listeners\WorkflowInitializeListener:
      autowire: true
      autoconfigure: true
      tags:
          - { name: doctrine.event_listener, event: postPersist }

  Devnet\WorkflowBundle\Core\WorkflowDefinitionRegistry: ~

  Devnet\WorkflowBundle\Twig\:
      resource: '../../Twig/*'
      autowire: true
      autoconfigure: true

  Devnet\WorkflowBundle\Security\:
      resource: '../../Security/*'
      autowire: true
      autoconfigure: true