<?php

namespace BoardMeetingBundle\Repository;

/**
 * BoardMeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardMeetingRepository extends \Doctrine\ORM\EntityRepository
{
}
