<?php

namespace BoardMeetingBundle\Repository;

/**
 * BoardMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
