<?php

namespace AccountBundle\Repository;

use AppBundle\Entity\Office;

/**
 * BankAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankAccountRepository extends \Doctrine\ORM\EntityRepository
{

    public function getBankAccountByOffice(Office $office = null, $fundType = null, $returnQB = false)
    {
        $qb = $this->createQueryBuilder('b');

        if ($office) {
            $qb->where('b.office = :office')->setParameter('office', $office);

        }
        $qb->andWhere('b.status = :status')->setParameter('status', 'approved');
        if ($fundType) {
            $qb->andWhere('b.fundType = :fundType')->setParameter('fundType', $fundType);
        }

        if ($returnQB) {
            return $qb;
        }

        return $qb->getQuery()->getResult();
    }

    public function getBankAccountAsArray(Office $office = null, $fundType = null)
    {
        $data = [];
        foreach ($this->getBankAccountByOffice($office, $fundType) as $bankAccount) {
            $data[$bankAccount->getId()] = $bankAccount->getName();
        }

        return $data;
    }
}
