<?php

namespace AccountBundle\Repository;

/**
 * BankBranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankBranchRepository extends \Doctrine\ORM\EntityRepository
{
}
