<?php

namespace AccountBundle\Repository;

use AppBundle\Repository\BaseRepository;

/**
 * BaseAccountsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseAccountsRepository extends BaseRepository
{
}
