<?php

namespace AccountBundle\Repository;

use AccountBundle\Entity\FundType;
use AppBundle\Entity\OfficeType;

/**
 * FundHeadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FundHeadRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy([], ['sort' => 'asc']);
    }

    public function fundHeadByFundType(FundType $fundType, OfficeType $officeType = null)
    {
        $data = ['fundType' => $fundType];
        if ($officeType) {
            $data['officeType'] = $officeType;
        }
        return $this->findBy($data, ['sort' => 'asc']);
    }

    public function fundHeadByFundTypeArray(FundType $fundType, OfficeType $officeType)
    {
        $data = [];

        /** @var FundHead $value */
        foreach ($this->fundHeadByFundType($fundType, $officeType) as $value) {
            $data[$value->getId()] = $value->getName();
        }

        return $data;
    }
}
