<?php

namespace AccountBundle\Repository;

use AccountBundle\Entity\ChequeReconciliation;
use AppBundle\Entity\Office;

/**
 * ReconciliationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReconciliationRepository extends BaseAccountsRepository
{
    public function getAllReconciliationMonth(Office $office)
    {
        $fundTypes = $this->_em->getRepository('AccountBundle:FundType')->getOfficeFundType(!$office->isBasb());

        $data = [];
        foreach ($fundTypes as $fundType) {
            if ($val = $this->getReconciliationMonthByFundType($fundType, $office)) {
                $data[$fundType->getId()] = $val;
            }
        }

        return $data;
    }

    public function getReconciliationMonthByFundType($fundType, $office)
    {
        // Last created reconciliation
        $lastReconciliation = $this->findOneBy(['fundType' => $fundType, 'office' => $office], ['year' => 'DESC', 'month' => 'DESC']);

        if ($lastReconciliation) {
            $d = (new \DateTime("{$lastReconciliation->getYear()}-{$lastReconciliation->getMonth()}-01"))->modify('+1 month');
            return [
                'year'  => (int)$d->format('Y'),
                'month' => (int)$d->format('m'),
                'string' => $d->format('F Y'),
                'date' => $d
            ];
        }

        // If no reconciliation created, new reconciliation date date should be voucher date
        $voucher = $this->_em->getRepository('AccountBundle:PaymentVoucher')->getFirstVoucher($fundType, $office);

        if ($voucher) {
            return [
                'year'  => (int)$voucher->getVoucherDate()->format('Y'),
                'month' => (int)$voucher->getVoucherDate()->format('m'),
                'string' => $voucher->getVoucherDate()->format('F Y'),
                'date' => $voucher->getVoucherDate()
            ];
        }

        return false;
    }

    /**
     * @param $bankAccount
     * @return ChequeReconciliation|bool
     */
    public function getLastReconciliation($office, $fundType)
    {
        /** @var ChequeReconciliation $recon */
        $recon = $this->findOneBy(['office' => $office, 'fundType' => $fundType], ['year' => 'DESC', 'month' => 'DESC']);

        return $recon && $recon->getStatus() != 'approved' ? $recon : false;
    }
}