<?php

namespace AccountBundle\Repository;

use AccountBundle\Entity\SanctionEntry;

/**
 * SanctionEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SanctionEntryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextNoteSheetNumber(SanctionEntry $sanctionEntry)
    {
        $qb = $this->createQueryBuilder('sanction_entry');
        $qb->select('COUNT(sanction_entry.id) as max_number');
        $qb->andWhere($qb->expr()->eq('sanction_entry.office', ':office'));
        $qb->andWhere($qb->expr()->eq('sanction_entry.fundType', ':fundType'));
        $qb->andWhere($qb->expr()->eq('sanction_entry.year', ':year'));

        $qb->setParameters([
            'office' => $sanctionEntry->getOffice(),
            'fundType' => $sanctionEntry->getFundType(),
            'year' => $sanctionEntry->getYear()
        ]);
        $maxNumber = $qb->getQuery()->getSingleScalarResult();

        return (int)$maxNumber+1;
    }
}
