<?php

namespace AccountBundle\Repository;

use AccountBundle\Entity\FundType;

/**
 * SanctionReceiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SanctionReceiveRepository extends SanctionEntryRepository
{
}
