<?php

namespace AccountBundle\Repository;

/**
 * SanctionMiscellaneousRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SanctionMiscellaneousRepository extends SanctionEntryRepository
{
}
