<?php

namespace AccountBundle\Repository;

use AccountBundle\Entity\FundType;

/**
 * VoucherDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoucherDetailRepository extends BaseAccountsRepository
{
    public function getReceiveSummary($year, FundType $fundType)
    {
        $qb = $this->createQueryBuilder('voucherDetail');
        $qb->join('voucherDetail.voucher', 'voucher');
        $qb->join('voucher.fundType', 'fundType');

        $qb->where($qb->expr()->eq('voucher.year', $year));
        $qb->andWhere($qb->expr()->eq('voucher.fundType', $fundType));
    }
}
