<?php

namespace WelfareBundle\Repository;

use AppBundle\Repository\BaseRepository;

/**
 * WelfareApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WelfareApplicationRepository extends BaseRepository
{

    public function getLastApplicationOfServiceMan($exServiceman)
    {
        $qb = $this->createQueryBuilder('w');
        $qb->where('w.serviceMan = :serviceMan')->setParameter('serviceMan', $exServiceman);
        $qb->andWhere('w.status != :status')->setParameter('status', 'rejected');
        $qb->orderBy('w.id', 'desc');
        $qb->setMaxResults(1);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
