services:
    MovementBundle\Workflow\:
        resource: '../../Workflow/*'
        autowire: true
        autoconfigure: true
        public: false
        tags:
            - {name: app.workflow_definition}

    MovementBundle\Listener\MovementWorkflowListener:
        autowire: true
        tags:
            - { name: kernel.event_subscriber }
