<?php

namespace FuneralBundle\Repository;

/**
 * FuneralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuneralRepository extends \Doctrine\ORM\EntityRepository
{
}
