<?php

namespace PersonnelBundle\Repository;

/**
 * EmploymentInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploymentInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
