<?php

namespace PersonnelBundle\Repository;

/**
 * ExAdditionalInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExAdditionalInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
