<?php

namespace PersonnelBundle\Repository;

/**
 * ExCareerInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExCareerInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
