<?php

namespace PersonnelBundle\Repository;

/**
 * ExEducationalInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExEducationalInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
