<?php

namespace PersonnelBundle\Repository;

/**
 * ExFamilyInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExFamilyInformationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFamilyMembers($serviceMan)
    {
        $rows = $this->findBy(['serviceman' => $serviceMan]);
        $members = [];
        foreach ($rows as $row) {
            $members[strtolower($row->getRelationType())] = $row;
        }
        return $members;
    }
}
