<?php

namespace PersonnelBundle\Repository;

/**
 * ExParentInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExParentInformationRepository extends \Doctrine\ORM\EntityRepository
{

}
