<?php

namespace PersonnelBundle\Repository;

/**
 * ExServicemanAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExServicemanAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
