<?php

namespace PersonnelBundle\Repository;

/**
 * ExServiceInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExServiceInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
