<?php

namespace PersonnelBundle\Repository;

/**
 * ExSpecialDiseaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExSpecialDiseaseRepository extends \Doctrine\ORM\EntityRepository
{
}
