<?php

namespace PersonnelBundle\Repository;

/**
 * ExTrainingInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExTrainingInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
