<?php

namespace PersonnelBundle\Repository;

/**
 * FamilyInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyInformationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFamilyByRelation($personnel, $relation)
    {
        return $this->findOneBy(['serviceman' => $personnel]);
    }
}
