<?php

namespace PersonnelBundle\Repository;

/**
 * FundReceivedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FundReceivedRepository extends \Doctrine\ORM\EntityRepository
{
}
