<?php

namespace PersonnelBundle\Repository;

/**
 * MilitaryPersonnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MilitaryPersonnelRepository extends \Doctrine\ORM\EntityRepository
{
}
