<?php

namespace PersonnelBundle\Repository;

/**
 * ServingPersonnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServingPersonnelRepository extends \Doctrine\ORM\EntityRepository
{
}
