<?php

namespace PersonnelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServingCivilianRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServingCivilianRepository extends EntityRepository
{
    public function getServingCivilianData($data)
    {
        if(!empty($data)) {
            $query= $this->createQueryBuilder('ex');

            if (!empty($data['office'])) {
                $query->join('ex.office', 'o');
                $query->andWhere('o.id = :rank');
                $query->setParameter('rank', $data['office']);
            }

            if (!empty($data['religion'])) {
                $query->andWhere('ex.religion = :religion');
                $query->setParameter('religion', $data['religion']);
            }

            if (!empty($data['gender'])) {
                $query->andWhere('ex.gender = :gender');
                $query->setParameter('gender', $data['gender']);
            }

            if (!empty($data['identityNumber'])) {
                $query->andWhere('ex.identityNumber = :identityNumber');
                $query->setParameter('identityNumber', $data['identityNumber']);
            }

            return $query->getQuery()->getResult();
        } else {
            return null;
        }
    }

    public function personalNo()
    {
        $query = $this->createQueryBuilder('p');
        $query->select('p.identityNumber as value');
        $result = $query->getQuery()->getResult();

        return $result;
    }
}
