services:
    NotificationBundle\Manager\NotificationManager:
        autowire: true
        autoconfigure: true

    NotificationBundle\Twig\NotificationExtension:
        autowire: true
        autoconfigure: true
