<?php

namespace BudgetBundle\Repository;

/**
 * BudgetHeadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetHeadRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChildBudgetHead()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->where($qb->expr()->isNotNull('b.parent'));

        return $qb->getQuery()->getResult();
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getParentBudgetHeadQb()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->where($qb->expr()->isNull('b.parent'));
        $qb->orderBy('b.sort', 'asc');
        $qb->addOrderBy('b.id', 'asc');

        return $qb;
    }

    public function getParentBudgetHead()
    {
        return $this->getParentBudgetHeadQb()->getQuery()->getResult();
    }
}
