<?php

namespace BudgetBundle\Repository;

use AppBundle\Entity\FinancialYear;
use AppBundle\Entity\Office;
use BudgetBundle\Entity\BudgetDetail;
use BudgetBundle\Entity\BudgetHead;
use BudgetBundle\Entity\BudgetSummary;
use BudgetBundle\Entity\BudgetSummaryDetail;

/**
 * BudgetSummaryDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetSummaryDetailRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateRequestAmount($data)
    {
        foreach ($data as $key => $amount) {
            /** @var BudgetSummaryDetail $bd */
            $bd = $this->find($key);

            if (!$bd) {
                continue;
            }

            $bd->setRequestAmount((float)$amount['current']);
            $bd->setSanctionAmount((float)$amount['current']);
            $bd->setAmount((float)$amount['current']);
            $bd->setNextYearProjectionAmount((float)$amount['next']);
            $bd->setAfterNextYearProjectionAmount((float)$amount['after-next']);
            $this->_em->flush();
        }
    }

    public function updateAmount($data)
    {
        foreach ($data as $key => $amount) {
            /** @var BudgetSummaryDetail $bd */
            $bd = $this->find($key);

            if (!$bd) {
                continue;
            }
            $bd->setAmount((float)$amount);
            $bd->setSanctionAmount($bd->getAmount());
            $bd->setAmendmentRequestAmount($bd->getAmount());
            $this->_em->flush();
        }
    }

    public function updateAmendmentRequestAmount($data)
    {
        foreach ($data as $key => $amount) {
            /** @var BudgetSummaryDetail $bd */
            $bd = $this->find($key);

            if (!$bd) {
                continue;
            }
            $bd->setAmendmentRequestAmount((float)$amount);
            $bd->setAmendmentSanctionAmount((float)$amount);
            $this->_em->flush();
        }
    }

    public function updateAmendmentSanctionAmount($data)
    {
        foreach ($data as $key => $amount) {
            /** @var BudgetSummaryDetail $bd */
            $bd = $this->find($key);

            if (!$bd) {
                continue;
            }
            $bd->setAmendmentSanctionAmount((float)$amount);
            $this->_em->flush();
        }
    }

    /**
     * @param BudgetSummary|mixed $budget
     * @return array
     */
    public function getBudgetSummaryAmount($budget)
    {
        $data = [];
        if (!$budget) return $data;

        /** @var BudgetSummaryDetail $budgetDetail */
        foreach ($budget->getBudgetSummaryDetails() as $budgetDetail) {
            $data[$budgetDetail->getBudgetHead()->getId()] = [
                'id'                            => $budgetDetail->getId(),
                'requestAmount'                 => $budgetDetail->getRequestAmount(),
                'amount'                        => $budgetDetail->getAmount(),
                'nextYearProjectionAmount'      => $budgetDetail->getNextYearProjectionAmount(),
                'afterNextYearProjectionAmount' => $budgetDetail->getAfterNextYearProjectionAmount(),
                'sanctionAmount'                => $budgetDetail->getSanctionAmount(),
                'amendmentRequestAmount'        => $budgetDetail->getAmendmentRequestAmount(),
                'amendmentSanctionAmount'       => $budgetDetail->getAmendmentSanctionAmount(),
                'remainingAmount'               => $budgetDetail->getRemainingAmount(),
                'distributedAmount'             => $budgetDetail->getDistributedAmount(),
            ];
        }

        return $data;
    }

    public function getBudgetSummaryAmountByYear($year)
    {
        $budget = $this->_em->getRepository('BudgetBundle:BudgetSummary')->getBudgetSummaryByYear($year);

        if (!$budget) {
            return ['data' => [], 'total' => ['requestAmount' => 0, 'amount' => 0]];
        }

        return $this->getBudgetSummaryAmountWithTotal($budget);
    }

    public function getBudgetSummaryAmountWithTotal($budget)
    {
        return [
            'data' => $this->getBudgetSummaryAmount($budget),
            'total' => $this->getTotalAmount($budget->getId()),
        ];
    }

    public function getTotalAmount($budgetId)
    {
        $qb = $this->createQueryBuilder('bd');

        $qb->select("SUM(bd.requestAmount) as requestAmount, SUM(bd.amount) amount, SUM(bd.sanctionAmount) as sanctionAmount, SUM(bd.amendmentRequestAmount) as amendmentRequestAmount, SUM(bd.amendmentSanctionAmount) as amendmentSanctionAmount, SUM(bd.remainingAmount) as remainingAmount, (SUM(bd.amount) - SUM(bd.remainingAmount)) as distributedAmount");
        $qb->join('bd.budgetSummary', 'budget');
        $qb->where($qb->expr()->eq('budget.id', $budgetId));
        $qb->groupBy('budget.id');

        return $qb->getQuery()->getSingleResult();
    }

    public function updateRemainingAmount(BudgetSummary $budgetSummary)
    {
        $result = $this->_em->getRepository('BudgetBundle:BudgetDetail')->getBudgetAmountOfAllHeadByFinancialYear($budgetSummary->getFinancialYear());

        /** @var BudgetSummaryDetail $budgetSummaryDetail */
        foreach ($budgetSummary->getBudgetSummaryDetails() as $budgetSummaryDetail) {
            $budgetHead = $budgetSummaryDetail->getBudgetHead();
            if (array_key_exists($budgetHead->getId(), $result)) {
                $budgetSummaryDetail->setRemainingAmount($budgetSummaryDetail->getAmount() - $result[$budgetHead->getId()]['amount']);
                $this->_em->persist($budgetSummaryDetail);
            }
        }

        $this->_em->flush();
    }

    public function getRemainingAmountOfHead(BudgetHead $budgetHead, FinancialYear $financialYear)
    {
        $qb = $this->createQueryBuilder('budgetSummaryDetail');
        $qb->join('budgetSummaryDetail.budgetSummary', 'budgetSummary');
        $qb->where($qb->expr()->eq('budgetSummary.financialYear', ':financialYear'));
        $qb->andWhere($qb->expr()->eq('budgetSummaryDetail.budgetHead', ':budgetHead'));
        $qb->setParameters(['financialYear' => $financialYear, 'budgetHead' => $budgetHead]);

        /** @var BudgetSummaryDetail $row */
        if ($row = $qb->getQuery()->getOneOrNullResult()) {
            return $row->getRemainingAmount();
        }

        return 0;
    }

    public function getAmounts($year, $status = null, Office $office = null)
    {
        $qb = $this->createQueryBuilder('bd');

        $qb->select("budgetHead.id as headId, bd.requestAmount as requestAmount, bd.amount as amount, bd.sanctionAmount as sanctionAmount, bd.amendmentRequestAmount as amendmentRequestAmount, bd.amendmentSanctionAmount as amendmentSanctionAmount, bd.remainingAmount as remainingAmount, (bd.amount - bd.remainingAmount) as distributedAmount, bd.nextYearProjectionAmount as nextYearProjectionAmount, bd.afterNextYearProjectionAmount as afterNextYearProjectionAmount");
        $qb->join('bd.budgetSummary', 'budget');
        $qb->join('bd.budgetHead', 'budgetHead');
        $qb->where($qb->expr()->eq('budget.financialYear', $year));

        if ($office) {
            $qb->andWhere($qb->expr()->eq('budget.office', ':office'));
            $qb->setParameter('office', $office);
        }

        if ($status) {
            $qb->andWhere("budget.{$status} = 'completed'");
        }

        $data = [];
        foreach ($qb->getQuery()->getResult() as $row) {
            $data[$row['headId']] = $row;
        }

        return $data;
    }

    public function getTotalAmountParentHeadWise($year, $status = null, Office $office = null)
    {
        $qb = $this->createQueryBuilder('bd');

        $qb->select("parent.id, SUM(bd.requestAmount) as requestAmount, SUM(bd.amount) amount, SUM(bd.sanctionAmount) as sanctionAmount, SUM(bd.amendmentRequestAmount) as amendmentRequestAmount, SUM(bd.amendmentSanctionAmount) as amendmentSanctionAmount, SUM(bd.remainingAmount) as remainingAmount, (SUM(bd.amount) - SUM(bd.remainingAmount)) as distributedAmount, SUM(bd.nextYearProjectionAmount) as nextYearProjectionAmount, SUM(bd.afterNextYearProjectionAmount) as afterNextYearProjectionAmount");
        $qb->join('bd.budgetSummary', 'budget');
        $qb->join('bd.budgetHead', 'budgetHead');
        $qb->join('budgetHead.parent', 'parent');
        $qb->where($qb->expr()->eq('budget.financialYear', $year));
        $qb->groupBy('parent.id');

        if ($office) {
            $qb->andWhere($qb->expr()->eq('budget.office', ':office'));
            $qb->setParameter('office', $office);
        }

        if ($status) {
            $qb->andWhere("budget.{$status} = 'completed'");
        }

        $data = [];
        foreach ($qb->getQuery()->getResult() as $row) {
            $data[$row['id']] = $row;
        }

        return $data;
    }

    public function getTotalAmountOfYear($year, $status = null, Office $office = null)
    {
        $qb = $this->createQueryBuilder('bd');

        $qb->select("SUM(bd.requestAmount) as requestAmount, SUM(bd.amount) amount, SUM(bd.sanctionAmount) as sanctionAmount, SUM(bd.amendmentRequestAmount) as amendmentRequestAmount, SUM(bd.amendmentSanctionAmount) as amendmentSanctionAmount, SUM(bd.remainingAmount) as remainingAmount, (SUM(bd.amount) - SUM(bd.remainingAmount)) as distributedAmount, SUM(bd.nextYearProjectionAmount) as nextYearProjectionAmount, SUM(bd.afterNextYearProjectionAmount) as afterNextYearProjectionAmount");
        $qb->join('bd.budgetSummary', 'budget');
        $qb->join('bd.budgetHead', 'budgetHead');
        $qb->join('budgetHead.parent', 'parent');
        $qb->where($qb->expr()->eq('budget.financialYear', $year));

        if ($office) {
            $qb->andWhere($qb->expr()->eq('budget.office', ':office'));
            $qb->setParameter('office', $office);
        }

        if ($status) {
            $qb->andWhere("budget.{$status} = 'completed'");
        }

        return $qb->getQuery()->getResult()[0];
    }

}
