<?php

namespace BudgetBundle\Repository;

use AppBundle\Entity\Office;
use AppBundle\Repository\BaseRepository;

/**
 * BudgetIncomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetIncomeRepository extends BaseRepository
{

    public function getAllHeadTotal($financialYear = null, Office $office = null, $duration = null)
    {
        $qb = $this->createQueryBuilder('bi');
        $qb->select('budgetHead.id, SUM(bi.amount) totalAmount');
        $qb->join('bi.budgetHead', 'budgetHead');
        $qb->where("bi.status = 'approved'");

        if ($financialYear) {
            $qb->andWhere($qb->expr()->eq('bi.financialYear', ':financialYear'));
            $qb->setParameter('financialYear', $financialYear);
        }

        if (!empty($duration)) {
            if (isset($duration['start'])) {
                $qb->andWhere($qb->expr()->gt('bi.createdAt', ':startDate'));
                $qb->setParameter('startDate', $duration['start']);
            }

            if (isset($duration['end'])) {
                $qb->andWhere($qb->expr()->lt('bi.createdAt', ':endDate'));
                $qb->setParameter('endDate', $duration['end']);
            }
        }

        $qb->groupBy('budgetHead.id');

        $data = [];

        foreach ($qb->getQuery()->getResult() as $row) {
            $data[$row['id']] = $row['totalAmount'];
        }

        return $data;
    }

    public function getAllParentHeadTotal($financialYear = null, $duration = null, $grandTotal = false, $office=null)
    {
        $qb = $this->createQueryBuilder('bi');
        $qb->select('SUM(bi.amount) totalAmount');
        $qb->join('bi.budgetHead', 'budgetHead');
        $qb->join('budgetHead.parent', 'parentBudgetHead');
        $qb->where("bi.status = 'approved'");

        if ($financialYear) {
            $qb->andWhere($qb->expr()->eq('bi.financialYear', ':financialYear'));
            $qb->setParameter('financialYear', $financialYear);
        }

        if (!empty($duration)) {
            if (isset($duration['start'])) {
                $qb->andWhere($qb->expr()->gt('bi.createdAt', ':startDate'));
                $qb->setParameter('startDate', $duration['start']);
            }

            if (isset($duration['end'])) {
                $qb->andWhere($qb->expr()->lt('bi.createdAt', ':endDate'));
                $qb->setParameter('endDate', $duration['end']);
            }
        }

        $data = [];
        if (!$grandTotal) {
            $qb->addSelect('parentBudgetHead.id');
            $qb->groupBy('parentBudgetHead.id');

            foreach ($qb->getQuery()->getResult() as $row) {
                $data[$row['id']] = $row['totalAmount'];
            }
        } else {
            $row = $qb->getQuery()->getOneOrNullResult();
            $data = $row ? $row['totalAmount'] : 0;
        }

        return $data;
    }

}
