<?php

namespace BudgetBundle\Repository;

use AppBundle\Entity\FinancialYear;
use AppBundle\Entity\Office;
use AppBundle\Utility\DateUtil;
use BudgetBundle\Entity\BaseBudget;
use BudgetBundle\Entity\Budget;
use BudgetBundle\Entity\BudgetDetail;
use BudgetBundle\Entity\FundRequest;
use Monolog\Handler\Curl\Util;

/**
 * BudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetRepository extends BaseBudgetRepository
{
    /**
     * @param $financialYear
     *
     * @return \BudgetBundle\Entity\Budget
     */
    public function initBudget($financialYear, $office)
    {
        $budget = new Budget();
        $budget->setFinancialYear($financialYear);
        $budget->setOffice($office);
        $this->_em->persist($budget);

        $budgetHeads = $this->_em->getRepository('BudgetBundle:BudgetHead')->getChildBudgetHead();

        foreach ($budgetHeads as $budgetHead) {
            $budgetDetail = new BudgetDetail();

            $budgetDetail->setBudgetHead($budgetHead);
            $budgetDetail->setBudget($budget);
            $this->_em->persist($budgetDetail);
        }

        $this->_em->flush();

        return $budget;
    }

    /**
     * @param $financialYear
     * @return null|object
     *
     */
    public function getBudgetByYear($financialYear, $office)
    {
        if (!$financialYear instanceof FinancialYear) {
            $financialYear = new FinancialYear($financialYear);
        }

        return $this->findOneBy(['financialYear' => $financialYear, 'office' => $office]);
    }

    public function getCurrentYearBudget(Office $office)
    {
        $financialYear = $this->_em->getRepository('AppBundle:FinancialYear')->find(
            DateUtil::getCurrentFinancialYear()
        );

        $param = ['financialYear' => $financialYear, 'office' => $office];
        return $this->findOneBy($param);
    }
}
