<?php

namespace BudgetBundle\Repository;

use AppBundle\Entity\FinancialYear;
use AppBundle\Entity\Office;
use AppBundle\Repository\BaseRepository;
use AppBundle\Utility\DateUtil;
use BudgetBundle\Entity\BudgetIncomeSummary;
use BudgetBundle\Entity\BudgetIncomeSummaryDetail;
use BudgetBundle\Entity\BudgetSummary;
use BudgetBundle\Entity\BudgetSummaryDetail;
use BudgetBundle\Entity\PreBudgetIncomeSummary;
use BudgetBundle\Entity\PreBudgetIncomeSummaryDetail;
use BudgetBundle\Entity\PreBudgetSummary;
use BudgetBundle\Entity\PreBudgetSummaryDetail;

/**
 * BudgetSummaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetIncomeSummaryRepository extends BaseRepository
{
    public function getCurrentYearBudgetSummary()
    {
        $financialYear = $this->_em->getRepository('AppBundle:FinancialYear')->find(DateUtil::getCurrentFinancialYear());

        return $this->findOneBy(['financialYear' => $financialYear]);
    }

    /**
     * @param FinancialYear $financialYear
     * @return BudgetIncomeSummary
     */
    public function initBudgetSummary(FinancialYear $financialYear, PreBudgetIncomeSummary $preBudget, Office $office)
    {
        $budget = new BudgetIncomeSummary();
        $budget->setStatus('draft');
        $budget->setFinancialYear($financialYear);
        $budget->setOffice($office);
        $this->_em->persist($budget);

        /** @var PreBudgetIncomeSummaryDetail $b */
        foreach ($preBudget->getPreBudgetSummaryDetails() as $b) {
            $budgetDetail = new BudgetIncomeSummaryDetail();

            $budgetDetail->setBudgetHead($b->getBudgetHead());
            $budgetDetail->setBudgetSummary($budget);

            $budgetDetail->setRequestAmount($b->getRequestAmount());
            $budgetDetail->setAmount($b->getRequestAmount());
            $budgetDetail->setNextYearProjectionAmount($b->getNextYearProjectionAmount());
            $budgetDetail->setAfterNextYearProjectionAmount($b->getAfterNextYearProjectionAmount());

            $this->_em->persist($budgetDetail);
        }

        $this->_em->flush();

        return $budget;
    }

    public function getBudgetSummaryByYear($year)
    {
        if (!$year instanceof FinancialYear) {
            $year = $this->_em->getRepository('AppBundle:FinancialYear')->find($year);
        }

        return $this->findOneBy(['financialYear' => $year]);
    }

    public function getBudgetSummaryViewUpdateData(BudgetIncomeSummary $budgetSummary)
    {
        $budgetYear = $budgetSummary->getFinancialYear()->getId();
        $budgetHead = $this->_em->getRepository('BudgetBundle:BudgetIncomeHead')->getParentBudgetHead();
        $budgetSummaryDetailRepo = $this->_em->getRepository('BudgetBundle:BudgetIncomeSummaryDetail');

        return [
            'budgetHead'           => $budgetHead,
            'budgetSummary'        => $budgetSummary,
            'budgetYear'           => $budgetYear,
            'budgetAmount'         => $budgetSummaryDetailRepo->getBudgetSummaryAmount($budgetSummary),
            'currentBudgetAmount'  => $budgetSummaryDetailRepo->getBudgetSummaryAmountByYear($budgetYear - 1),
            'previousBudgetAmount' => $budgetSummaryDetailRepo->getBudgetSummaryAmountByYear($budgetYear - 2),
        ];
    }
}