<?php

namespace BudgetBundle\Repository;

use AppBundle\Entity\FinancialYear;
use AppBundle\Repository\BaseRepository;
use BudgetBundle\Entity\BudgetHead;
use BudgetBundle\Entity\BudgetSummary;
use BudgetBundle\Entity\BudgetSummaryDetail;
use BudgetBundle\Entity\PreBudgetIncomeSummary;
use BudgetBundle\Entity\PreBudgetIncomeSummaryDetail;
use BudgetBundle\Entity\PreBudgetSummary;
use BudgetBundle\Entity\PreBudgetSummaryDetail;

/**
 * BudgetSummaryDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreBudgetIncomeSummaryDetailRepository extends BaseRepository
{
    public function updateRequestAmount($data)
    {
        foreach ($data as $key => $amount) {
            /** @var PreBudgetSummaryDetail $bd */
            $bd = $this->find($key);

            if (!$bd) {
                continue;
            }

            $bd->setRequestAmount((float)$amount['current']);
            $bd->setAmount((float)$amount['current']);
            $bd->setNextYearProjectionAmount((float)$amount['next']);
            $bd->setAfterNextYearProjectionAmount((float)$amount['after-next']);
            $this->_em->flush();
        }
    }

    /**
     * @param PreBudgetIncomeSummary|mixed $budget
     * @return array
     */
    public function getBudgetSummaryAmount($budget)
    {
        $data = [];
        if (!$budget) return $data;

        /** @var PreBudgetIncomeSummaryDetail $budgetDetail */
        foreach ($budget->getPreBudgetSummaryDetails() as $budgetDetail) {
            $data[$budgetDetail->getBudgetHead()->getId()] = [
                'id'                            => $budgetDetail->getId(),
                'requestAmount'                 => $budgetDetail->getRequestAmount(),
                'amount'                        => $budgetDetail->getAmount(),
                'nextYearProjectionAmount'      => $budgetDetail->getNextYearProjectionAmount(),
                'afterNextYearProjectionAmount' => $budgetDetail->getAfterNextYearProjectionAmount(),
            ];
        }

        return $data;
    }

    public function getBudgetSummaryAmountByYear($year)
    {
        $budget = $this->_em->getRepository('BudgetBundle:PreBudgetIncomeSummary')->getPreBudgetSummaryByYear($year);

        if (!$budget) {
            return ['data' => [], 'total' => ['requestAmount' => 0, 'amount' => 0]];
        }

        return $this->getBudgetSummaryAmountWithTotal($budget);
    }

    public function getBudgetSummaryAmountWithTotal($budget)
    {
        return [
            'data' => $this->getBudgetSummaryAmount($budget),
            'total' => $this->getTotalAmount($budget->getId()),
        ];
    }

    public function getTotalAmount($budgetId)
    {
        $qb = $this->createQueryBuilder('bd');

        $qb->select("SUM(bd.requestAmount) as requestAmount, SUM(bd.amount) amount");
        $qb->join('bd.budgetSummary', 'budget');
        $qb->where($qb->expr()->eq('budget.id', $budgetId));
        $qb->groupBy('budget.id');

        return $qb->getQuery()->getSingleResult();
    }

    public function updateRemainingAmount(BudgetSummary $budgetSummary)
    {
        $result = $this->_em->getRepository('BudgetBundle:BudgetDetail')->getBudgetAmountOfAllHeadByFinancialYear($budgetSummary->getFinancialYear());

        /** @var BudgetSummaryDetail $budgetSummaryDetail */
        foreach ($budgetSummary->getBudgetSummaryDetails() as $budgetSummaryDetail) {
            $budgetHead = $budgetSummaryDetail->getBudgetHead();
            if (array_key_exists($budgetHead->getId(), $result)) {
                $budgetSummaryDetail->setRemainingAmount($budgetSummaryDetail->getAmount() - $result[$budgetHead->getId()]['amount']);
                $this->_em->persist($budgetSummaryDetail);
            }
        }

        $this->_em->flush();
    }

    public function getRemainingAmountOfHead(BudgetHead $budgetHead, FinancialYear $financialYear)
    {
        $qb = $this->createQueryBuilder('budgetSummaryDetail');
        $qb->join('budgetSummaryDetail.budgetSummary', 'budgetSummary');
        $qb->where($qb->expr()->eq('budgetSummary.financialYear', ':financialYear'));
        $qb->andWhere($qb->expr()->eq('budgetSummaryDetail.budgetHead', ':budgetHead'));
        $qb->setParameters(['financialYear' => $financialYear, 'budgetHead' => $budgetHead]);

        /** @var BudgetSummaryDetail $row */
        if ($row = $qb->getQuery()->getOneOrNullResult()) {
            return $row->getRemainingAmount();
        }

        return 0;
    }

    public function getAmounts($year, $status = null)
    {
        $qb = $this->createQueryBuilder('bd');

        $qb->select("budgetHead.id as headId, bd.requestAmount as requestAmount, bd.amount as amount, bd.nextYearProjectionAmount as nextYearProjectionAmount, bd.afterNextYearProjectionAmount as afterNextYearProjectionAmount");
        $qb->join('bd.budgetSummary', 'budget');
        $qb->join('bd.budgetHead', 'budgetHead');
        $qb->where($qb->expr()->eq('budget.financialYear', $year));

        if ($status) {
            $qb->andWhere("budget.{$status} = 'approved'");
        }

        $data = [];
        foreach ($qb->getQuery()->getResult() as $row) {
            $data[$row['headId']] = $row;
        }

        return $data;
    }

    public function getTotalAmountParentHeadWise($year, $status = null)
    {
        $qb = $this->createQueryBuilder('bd');

        $qb->select("parent.id, SUM(bd.requestAmount) as requestAmount, SUM(bd.amount) amount, SUM(bd.nextYearProjectionAmount) as nextYearProjectionAmount, SUM(bd.afterNextYearProjectionAmount) as afterNextYearProjectionAmount");
        $qb->join('bd.budgetSummary', 'budget');
        $qb->join('bd.budgetHead', 'budgetHead');
        $qb->join('budgetHead.parent', 'parent');
        $qb->where($qb->expr()->eq('budget.financialYear', $year));
        $qb->groupBy('parent.id');

        if ($status) {
            $qb->andWhere("budget.{$status} = 'approved'");
        }

        $data = [];
        foreach ($qb->getQuery()->getResult() as $row) {
            $data[$row['id']] = $row;
        }

        return $data;
    }

    public function getTotalAmountOfYear($year, $status = null)
    {
        $qb = $this->createQueryBuilder('bd');

        $qb->select("SUM(bd.requestAmount) as requestAmount, SUM(bd.amount) amount, SUM(bd.nextYearProjectionAmount) as nextYearProjectionAmount, SUM(bd.afterNextYearProjectionAmount) as afterNextYearProjectionAmount");
        $qb->join('bd.budgetSummary', 'budget');
        $qb->join('bd.budgetHead', 'budgetHead');
        $qb->join('budgetHead.parent', 'parent');
        $qb->where($qb->expr()->eq('budget.financialYear', $year));

        if ($status) {
            $qb->andWhere("budget.{$status} = 'approved'");
        }

        return $qb->getQuery()->getResult()[0];
    }

}
