<?php

namespace BudgetBundle\Repository;

use AppBundle\Entity\FinancialYear;
use AppBundle\Entity\Office;
use AppBundle\Repository\BaseRepository;
use AppBundle\Utility\DateUtil;
use BudgetBundle\Entity\BudgetSummary;
use BudgetBundle\Entity\BudgetSummaryDetail;
use BudgetBundle\Entity\PreBudgetSummary;
use BudgetBundle\Entity\PreBudgetSummaryDetail;

/**
 * BudgetSummaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreBudgetSummaryRepository extends BaseRepository
{

    public function getCurrentYearBudgetSummary()
    {
        $financialYear = $this->_em->getRepository('AppBundle:FinancialYear')->find(DateUtil::getCurrentFinancialYear());

        return $this->findOneBy(['financialYear' => $financialYear]);
    }

    /**
     * @param FinancialYear $financialYear
     * @return PreBudgetSummary
     */
    public function initBudgetSummary(FinancialYear $financialYear, Office $office)
    {
        $budget = new PreBudgetSummary();
        $budget->setStatus('draft');
        $budget->setFinancialYear($financialYear);
        $budget->setOffice($office);
        $this->_em->persist($budget);

        $budgetHeads = $this->_em->getRepository('BudgetBundle:BudgetHead')->getChildBudgetHead();

        foreach ($budgetHeads as $budgetHead) {
            $budgetDetail = new PreBudgetSummaryDetail();

            $budgetDetail->setBudgetHead($budgetHead);
            $budgetDetail->setBudgetSummary($budget);
            $this->_em->persist($budgetDetail);
        }

        $this->_em->flush();

        return $budget;
    }

    public function getPreBudgetSummaryByYear($year)
    {
        if (!$year instanceof FinancialYear) {
            $year = $this->_em->getRepository('AppBundle:FinancialYear')->find($year);
        }

        return $this->findOneBy(['financialYear' => $year]);
    }

    public function getPreBudgetSummaryViewUpdateData(PreBudgetSummary $budgetSummary)
    {
        $budgetYear = $budgetSummary->getFinancialYear()->getId();
        $budgetHead = $this->_em->getRepository('BudgetBundle:BudgetHead')->getParentBudgetHead();
        $budgetSummaryDetailRepo = $this->_em->getRepository('BudgetBundle:PreBudgetSummaryDetail');

        return [
            'budgetHead'           => $budgetHead,
            'budgetSummary'        => $budgetSummary,
            'budgetYear'           => $budgetYear,
            'budgetAmount'         => $budgetSummaryDetailRepo->getBudgetSummaryAmount($budgetSummary),
            'currentBudgetAmount'  => $budgetSummaryDetailRepo->getBudgetSummaryAmountByYear($budgetYear - 1),
            'previousBudgetAmount' => $budgetSummaryDetailRepo->getBudgetSummaryAmountByYear($budgetYear - 2),
        ];
    }
}