<?php

namespace MedicalBundle\Repository;

use AppBundle\Repository\BaseRepository;

/**
 * InventoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryRepository extends BaseRepository
{
}
