<?php

namespace MedicalBundle\Repository;

use AppBundle\Repository\BaseRepository;

/**
 * MedicineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicineRepository extends BaseRepository
{
    public function getQueryBuilderForAllEnabledMedicine()
    {
        $qb = $this->createQueryBuilder('m');
        $qb->orderBy('m.sort', 'asc');

        return $qb->andWhere($qb->expr()->eq('m.enabled', TRUE));
    }

    public function getMedicines()
    {
        return $this->getQueryBuilderForAllEnabledMedicine()->getQuery()->getResult();
    }

    public function getMedicinesAsArray()
    {
        $data = [];
        foreach ($this->getMedicines() as $medicine) {
            $data[$medicine->getId()] = $medicine->getName();
        }

        return $data;
    }
}
