<?php

namespace MedicalBundle\Repository;

use AppBundle\Entity\Office;
use AppBundle\Repository\BaseRepository;
use MedicalBundle\Entity\Dispensary;

/**
 * RequisitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequisitionRepository extends BaseRepository
{
    public function getQueryBuilder($params)
    {
        $qb = $this->createQueryBuilder('requisition');

        if (isset($params['office']) && $params['office'] instanceof Office) {
            $qb->andWhere($qb->expr()->eq('requisition.office', ':office'));
            $qb->setParameter('office', $params['office']);
        }
        if (isset($params['dispensary']) &&  $params['dispensary'] instanceof Dispensary) {
            $qb->andWhere($qb->expr()->eq('requisition.dispensary', ':dispensary'));
            $qb->setParameter('dispensary', $params['dispensary']);
        }

        return $qb;
    }

    public function getRequisitionForOffice(Office $office)
    {
        $dispensaries = $this->_em->getRepository('MedicalBundle:Dispensary')->getDespensariesForOffice($office);
        $qb = $this->getQueryBuilder(['office' => $office]);
        $qb->orderBy('requisition.createdAt', 'desc');
        $qb->addOrderBy('requisition.dispensary', 'asc');
        $qb->setMaxResults(count($dispensaries));

        return $qb->getQuery()->getResult();
    }
}