<?php

namespace MedicalBundle\Repository;

use AppBundle\Repository\BaseRepository;

/**
 * RequisitionDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequisitionDetailRepository extends BaseRepository
{
}
