<?php

namespace MedicalBundle\Repository;

use AppBundle\Repository\BaseRepository;
use MedicalBundle\Entity\Dispensary;
use MedicalBundle\Entity\Medicine;
use MedicalBundle\Entity\Stock;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends BaseRepository
{
    public function getQueryBuilderForStock($params)
    {
        $qb = $this->createQueryBuilder('stock');

        if (isset($params['dispensary']) && $params['dispensary'] instanceof Dispensary){
            $qb->andWhere($qb->expr()->eq('stock.dispensary', ':dispensary'));
            $qb->setParameter('dispensary', $params['dispensary']);
        }

        if (isset($params['medicine']) && $params['medicine'] instanceof Medicine){
            $qb->andWhere($qb->expr()->eq('stock.medicine', ':medicine'));
            $qb->setParameter('medicine', $params['medicine']);
        }

        return $qb;
    }
    public function getStocks($params = [])
    {
        return $this->getQueryBuilderForStock($params)->getQuery()->getResult();
    }

    public function getStocksAsArray($dispensary = null, $medicine = null)
    {
        $data = [];
        /** @var Stock $stock */
        foreach ($this->getStocksByDispensary($dispensary) as $stock) {
            $data[$stock->getMedicine()->getId()] = $stock->getBalance();
        }

        return $data;
    }

    public function getStocksByDispensary($dispensary)
    {
        return $this->getQueryBuilderForStock(['dispensary' => $dispensary])->getQuery()->getResult();
    }
}
